Vagrant.configure("2") do |config|
  config.vm.box = "bento/centos-8.2"
  config.vm.box_version = "202006.16.0"
  config.vm.synced_folder "./", "/vagrant", owner: "vagrant", mount_options: ["dmode=775,fmode=600"]
  
  config.vm.define "vm3" do |vm3|
    vm3.vm.network  "private_network", ip: "192.168.33.13"
    vm3.vm.network  "forwarded_port", guest: 80, host: 13080 
    vm3.vm.hostname = "1655lab3"
    vm3.vm.provider "virtualbox" do |vb|
      vb.name = "1655lab3"
      vb.memory = "2048"
    end
  end
end
