---
# tasks file for nginx
- name: Ensure Nginx Installed
  package: name=nginx
  become: yes
  
- name: Deploy Config File
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify:
    - reload nginx
  become: yes
  
- name: start and enable nginx
  service: name=nginx state=started enabled=yes
  become: yes
